# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PG0yCsIVcWB7_3gTbAfbW24SWFOXO_f
"""

import pandas as pd
import pandas_ta as ta
df=pd.read_csv("/content/Book2.csv")
ta.supertrend(high=df["high"],low=df["low"],close=df["close"],period=7,multiplier=3)

df['sup']=ta.supertrend(high=df["high"],low=df["low"],close=df["close"],period=7,multiplier=3)["SUPERT_7_3.0"]
df.head(20)

df.tail(20)

df["Buy_signal"]=0
df["Sell_signal"]=0
n=7
for i in range(n,len(df)):
    if df["close"][i-1]<=df["sup"][i-1] and df["close"][i]>df["sup"][i]:
        df["Buy_signal"][i]=1
    if df["close"][i-1]>=df["sup"][i-1] and df["close"][i]<df["sup"][i]:
        df["Sell_signal"][i]=1
df

df[(df["Buy_signal"]>0)|(df["Sell_signal"]>0)]